<?xml version="1.0" encoding="UTF-8"?>

<definitions name="ShapeToolService"
             targetNamespace="http://example.com/shapetool"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://example.com/shapetool"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <types>
        <xsd:schema>
            <xsd:import namespace="http://example.com/shapetool"
                        schemaLocation="shapetool.xsd"/>
        </xsd:schema>
    </types>

    <!-- Messages -->

    <message name="circleAreaRequest">
        <part name="parameters" element="tns:circleAreaRequest"/>
    </message>

    <message name="circleAreaResponse">
        <part name="parameters" element="tns:circleAreaResponse"/>
    </message>

    <message name="squareAreaRequest">
        <part name="parameters" element="tns:squareAreaRequest"/>
    </message>

    <message name="squareAreaResponse">
        <part name="parameters" element="tns:squareAreaResponse"/>
    </message>

    <message name="rectangleAreaRequest">
        <part name="parameters" element="tns:rectangleAreaRequest"/>
    </message>

    <message name="rectangleAreaResponse">
        <part name="parameters" element="tns:rectangleAreaResponse"/>
    </message>

    <message name="parallelogramAreaRequest">
        <part name="parameters" element="tns:parallelogramAreaRequest"/>
    </message>

    <message name="parallelogramAreaResponse">
        <part name="parameters" element="tns:parallelogramAreaResponse"/>
    </message>

    <message name="triangleAreaRequest">
        <part name="parameters" element="tns:triangleAreaRequest"/>
    </message>

    <message name="triangleAreaResponse">
        <part name="parameters" element="tns:triangleAreaResponse"/>
    </message>

    <!-- Port Type -->

    <portType name="ShapeToolPortType">

        <operation name="circleArea">
            <input message="tns:circleAreaRequest"/>
            <output message="tns:circleAreaResponse"/>
        </operation>

        <operation name="squareArea">
            <input message="tns:squareAreaRequest"/>
            <output message="tns:squareAreaResponse"/>
        </operation>

        <operation name="rectangleArea">
            <input message="tns:rectangleAreaRequest"/>
            <output message="tns:rectangleAreaResponse"/>
        </operation>

        <operation name="parallelogramArea">
            <input message="tns:parallelogramAreaRequest"/>
            <output message="tns:parallelogramAreaResponse"/>
        </operation>

        <operation name="triangleArea">
            <input message="tns:triangleAreaRequest"/>
            <output message="tns:triangleAreaResponse"/>
        </operation>

    </portType>

    <!-- Binding -->

    <binding name="ShapeToolBinding" type="tns:ShapeToolPortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>

        <operation name="circleArea">
            <soap:operation soapAction="circleArea"/>
            <input><soap:body use="literal"/></input>
            <output><soap:body use="literal"/></output>
        </operation>

        <operation name="squareArea">
            <soap:operation soapAction="squareArea"/>
            <input><soap:body use="literal"/></input>
            <output><soap:body use="literal"/></output>
        </operation>

        <operation name="rectangleArea">
            <soap:operation soapAction="rectangleArea"/>
            <input><soap:body use="literal"/></input>
            <output><soap:body use="literal"/></output>
        </operation>

        <operation name="parallelogramArea">
            <soap:operation soapAction="parallelogramArea"/>
            <input><soap:body use="literal"/></input>
            <output><soap:body use="literal"/></output>
        </operation>

        <operation name="triangleArea">
            <soap:operation soapAction="triangleArea"/>
            <input><soap:body use="literal"/></input>
            <output><soap:body use="literal"/></output>
        </operation>

    </binding>

    <!-- Service -->

    <service name="ShapeToolService">
        <port name="ShapeToolPort" binding="tns:ShapeToolBinding">
            <soap:address location="http://localhost:8080/shapetool"/>
        </port>
    </service>

</definitions>